### PR TITLE
fixed dependency

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@jjr840430 instead of `$(brew --prefix openssl)` inside a Formula, you can do this instead `Formula["openssl"].prefix`.

**Comment by jjr840430** [comment]
@ronaldtse When I used Formula["openssl"].prefix, I got the following issue while compiling.
superenv removed: -I/usr/local/opt/openssl/include -g -02
So detecting openssl in running configure script, but compilation is failed.

**Comment by jjr840430** [comment]
==> ./configure --prefix=/usr/local/Cellar/retrace/HEAD-9f22556 --with-openssl=/usr/local/opt/openssl --mandir=/usr/local/Cellar/retrace/HEAD-9f22556/share/m
==> make install
Last 15 lines from /Users/macman/Library/Logs/Homebrew/retrace/03.make:
install

Making install in src
  CC       libretrace_la-char.lo
  CC       libretrace_la-common.lo
  CC       libretrace_la-dir.lo
  CC       libretrace_la-dlopen.lo
In file included from common.c:78:
./ssl.h:9:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[1]: *** [libretrace_la-common.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

**Comment by jjr840430** [comment]
clang called with: -DHAVE_CONFIG_H -I. -I.. -I/usr/local/opt/openssl/include -I/usr/local/opt/openssl/include -mmacosx-version-min=10.12 -D_DARWIN_C_SOURCE -MT libretrace_la-dir.lo -MD -MP -MF .deps/libretrace_la-dir.Tpo -c dir.c -o libretrace_la-dir.o
superenv removed:  -I/usr/local/opt/openssl/include -I/usr/local/opt/openssl/include
superenv added:    -pipe -w -Os -march=native -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=native -DHAVE_CONFIG_H -I. -I.. -mmacosx-version-min=10.12 -D_DARWIN_C_SOURCE -MT libretrace_la-dir.lo -MD -MP -MF .deps/libretrace_la-dir.Tpo -c dir.c -o libretrace_la-dir.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers

**Comment by ronaldtse** [comment]
You can see other examples in homebrew:

https://github.com/Homebrew/homebrew-core/blob/5894035f8d13ec2a96edb44b892f2e1475c333ae/Formula/xaric.rb
```ruby
"--with-openssl=#{Formula["openssl"].opt_prefix}"
```

Does this work?

**Comment by ronaldtse** [comment]
With includes and prefix:

https://github.com/Homebrew/homebrew-core/blob/a757e184f1382db6a30379aa5333a96dc578b7cb/Formula/snort.rb
```ruby
    openssl = Formula["openssl"]
      --with-openssl-includes=#{openssl.opt_include}
      --with-openssl-libraries=#{openssl.opt_lib}
```

**Pull request merged**
